// Generated by scripts/generate-tokens.mjs from pencil-variables.json. Do not edit.

export const THEME_MODES = ["dark","light"] as const;

export type ThemeMode = (typeof THEME_MODES)[number];

export const DEFAULT_THEME_MODE: ThemeMode = "dark";

export const THEME_COLOR_SCHEME: Record<ThemeMode, "dark" | "light"> = {"dark":"dark","light":"light"};

export type TokenName =
  | "color-accent-primary"
  | "color-bg-canvas"
  | "color-border-default"
  | "color-diff-add"
  | "color-diff-add-bg"
  | "color-diff-done"
  | "color-diff-done-bg"
  | "color-diff-modify"
  | "color-diff-modify-bg"
  | "color-diff-remove"
  | "color-diff-remove-bg"
  | "color-favorite"
  | "color-favorite-on"
  | "color-icon-default"
  | "color-node-character"
  | "color-node-event"
  | "color-node-item"
  | "color-node-manuscript"
  | "color-node-organization"
  | "color-node-place"
  | "color-node-worldview"
  | "color-scrim-dialog"
  | "color-scrim-modal"
  | "color-scrim-strong"
  | "color-shadow-dialog"
  | "color-shadow-menu"
  | "color-state-hover"
  | "color-state-selected"
  | "color-surface-alpha0"
  | "color-surface-default"
  | "color-surface-icon"
  | "color-surface-icon-hover"
  | "color-surface-navigation"
  | "color-surface-raised"
  | "color-surface-topbar"
  | "color-text-on-accent"
  | "color-text-primary"
  | "color-text-secondary"
  | "control-height"
  | "doc-content-width"
  | "font-family-mono"
  | "font-family-ui"
  | "font-size-body"
  | "font-size-context"
  | "font-size-heading"
  | "font-size-heading-lg"
  | "font-size-label"
  | "font-size-manuscript-body"
  | "font-size-manuscript-title"
  | "icon-weight-default"
  | "line-height-body"
  | "line-height-context"
  | "line-height-manuscript-body"
  | "line-height-manuscript-title"
  | "property-label-width"
  | "property-row-height"
  | "radius-card"
  | "radius-control"
  | "space-1"
  | "space-2"
  | "space-3"
  | "space-4"
  | "space-6"
  | "space-7";

export const TOKEN_PREFIX = "--lk-";

export function cssVar(name: TokenName): string {
  return `var(${TOKEN_PREFIX}${name})`;
}
