import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

const TOKENS_DIR = new URL("../src/design-system/tokens/", import.meta.url);
const SOURCE_URL = new URL("pencil-variables.json", TOKENS_DIR);
const CSS_URL = new URL("tokens.css", TOKENS_DIR);
const TS_URL = new URL("tokens.ts", TOKENS_DIR);
const PREFIX = "--lk-";
const THEME_AXIS = "mode";
const HEADER =
  "Generated by scripts/generate-tokens.mjs from pencil-variables.json. Do not edit.";

const UNITLESS = [/^line-height-/, /^icon-weight-/];

function formatNumber(name, value) {
  return UNITLESS.some((pattern) => pattern.test(name))
    ? String(value)
    : `${value}px`;
}

function formatValue(name, type, value) {
  if (type === "number") return formatNumber(name, value);
  if (type === "string") return JSON.stringify(value);
  return value.toLowerCase();
}

function relativeLuminance(hex) {
  const channels = hex
    .replace("#", "")
    .slice(0, 6)
    .match(/../g)
    .map((pair) => Number.parseInt(pair, 16) / 255)
    .map((c) => (c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4));
  return 0.2126 * channels[0] + 0.7152 * channels[1] + 0.0722 * channels[2];
}

function valueForMode(definition, mode) {
  const entry = definition.value.find(
    (candidate) => candidate.theme?.[THEME_AXIS] === mode,
  );
  if (!entry) throw new Error(`Missing ${mode} value`);
  return entry.value;
}

export function buildTokens(source) {
  const modes = source.themes?.[THEME_AXIS];
  if (!Array.isArray(modes) || modes.length === 0) {
    throw new Error(`Design file has no "${THEME_AXIS}" theme axis`);
  }
  const entries = Object.entries(source.variables).sort(([a], [b]) =>
    a.localeCompare(b),
  );
  const themed = entries.filter(([, def]) => Array.isArray(def.value));
  const shared = entries.filter(([, def]) => !Array.isArray(def.value));

  const canvas = source.variables["color-bg-canvas"];
  if (!canvas)
    throw new Error("color-bg-canvas is required to infer color-scheme");
  const colorScheme = Object.fromEntries(
    modes.map((mode) => [
      mode,
      relativeLuminance(valueForMode(canvas, mode)) < 0.5 ? "dark" : "light",
    ]),
  );

  const block = (selector, lines) =>
    `${selector} {\n${lines.map((line) => `  ${line}`).join("\n")}\n}\n`;

  const cssParts = [
    `/* ${HEADER} */\n`,
    block(
      ":root",
      shared.map(
        ([name, def]) =>
          `${PREFIX}${name}: ${formatValue(name, def.type, def.value)};`,
      ),
    ),
    ...modes.map((mode, index) =>
      block(
        index === 0
          ? `:root,\n:root[data-theme="${mode}"]`
          : `:root[data-theme="${mode}"]`,
        [
          `color-scheme: ${colorScheme[mode]};`,
          ...themed.map(
            ([name, def]) =>
              `${PREFIX}${name}: ${formatValue(name, def.type, valueForMode(def, mode))};`,
          ),
        ],
      ),
    ),
  ];

  const names = entries.map(([name]) => name);
  const ts = [
    `// ${HEADER}`,
    "",
    `export const THEME_MODES = ${JSON.stringify(modes)} as const;`,
    "",
    "export type ThemeMode = (typeof THEME_MODES)[number];",
    "",
    `export const DEFAULT_THEME_MODE: ThemeMode = ${JSON.stringify(modes[0])};`,
    "",
    `export const THEME_COLOR_SCHEME: Record<ThemeMode, "dark" | "light"> = ${JSON.stringify(colorScheme)};`,
    "",
    "export type TokenName =",
    ...names.map(
      (name, index) =>
        `  | ${JSON.stringify(name)}${index === names.length - 1 ? ";" : ""}`,
    ),
    "",
    `export const TOKEN_PREFIX = ${JSON.stringify(PREFIX)};`,
    "",
    "export function cssVar(name: TokenName): string {",
    "  return `var(${TOKEN_PREFIX}${name})`;",
    "}",
    "",
  ].join("\n");

  return { css: cssParts.join("\n"), ts };
}

async function main(args) {
  const source = JSON.parse(await readFile(SOURCE_URL, "utf8"));
  const { css, ts } = buildTokens(source);

  if (args.includes("--check")) {
    const [currentCss, currentTs] = await Promise.all([
      readFile(CSS_URL, "utf8").catch(() => ""),
      readFile(TS_URL, "utf8").catch(() => ""),
    ]);
    if (currentCss !== css || currentTs !== ts) {
      console.error(
        "Design tokens are out of date with pencil-variables.json. Run pnpm tokens.",
      );
      process.exitCode = 1;
      return;
    }
    console.log("Design tokens match pencil-variables.json.");
    return;
  }

  await Promise.all([writeFile(CSS_URL, css), writeFile(TS_URL, ts)]);
  console.log(
    `Generated ${Object.keys(source.variables).length} tokens for modes: ${source.themes[THEME_AXIS].join(", ")}.`,
  );
}

if (fileURLToPath(import.meta.url) === resolve(process.argv[1] ?? "")) {
  await main(process.argv.slice(2));
}
