import {
  ArchiveRestore,
  ArrowDownWideNarrow,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Bold,
  Book,
  BookOpen,
  Bug,
  Building2,
  CalendarDays,
  ChartGantt,
  ChartNoAxesGantt,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsLeft,
  ChevronsRight,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleDot,
  CircleHelp,
  CircleUserRound,
  Clock3,
  CloudCheck,
  CloudOff,
  CloudRain,
  Copy,
  Download,
  Ellipsis,
  ExternalLink,
  File,
  FilePlus,
  FileStack,
  FileText,
  FileType,
  FileX,
  Filter,
  Folder,
  FolderInput,
  FolderMinus,
  FolderOpen,
  FolderPlus,
  Gem,
  GitCompareArrows,
  Globe,
  GripVertical,
  Hash,
  History,
  Home,
  Image,
  Info,
  Italic,
  KeyRound,
  LayoutGrid,
  Library,
  Lightbulb,
  List,
  ListFilter,
  ListIndentDecrease,
  ListIndentIncrease,
  ListOrdered,
  ListPlus,
  LoaderCircle,
  Lock,
  LockOpen,
  LogOut,
  Mail,
  Map,
  MapPin,
  Maximize,
  MessageSquare,
  MessageSquarePlus,
  Minus,
  Monitor,
  Moon,
  MoveHorizontal,
  MoveVertical,
  NotebookPen,
  NotebookTabs,
  Orbit,
  Package,
  PanelBottom,
  PanelBottomClose,
  PanelLeft,
  PanelRight,
  PanelRightClose,
  PanelsTopLeft,
  PenLine,
  Pencil,
  Plus,
  Printer,
  Redo2,
  RefreshCw,
  Rocket,
  RotateCcw,
  RotateCw,
  Save,
  Scan,
  Scroll,
  Search,
  SearchX,
  Send,
  Settings,
  Sparkles,
  Square,
  Star,
  StickyNote,
  Strikethrough,
  Sun,
  SunMoon,
  Tag,
  Trash2,
  TriangleAlert,
  Type,
  Underline,
  Undo2,
  Upload,
  UserCog,
  UserRound,
  UserX,
  UsersRound,
  Waypoints,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const ICONS = {
  "archive-restore": ArchiveRestore,
  "arrow-down-wide-narrow": ArrowDownWideNarrow,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  "arrow-up-right": ArrowUpRight,
  bold: Bold,
  book: Book,
  "book-open": BookOpen,
  bug: Bug,
  "building-2": Building2,
  "calendar-days": CalendarDays,
  "chart-gantt": ChartGantt,
  "chart-no-axes-gantt": ChartNoAxesGantt,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "chevrons-left": ChevronsLeft,
  "chevrons-right": ChevronsRight,
  circle: Circle,
  "circle-alert": CircleAlert,
  "circle-check": CircleCheck,
  "circle-dot": CircleDot,
  "circle-help": CircleHelp,
  "circle-user-round": CircleUserRound,
  "clock-3": Clock3,
  "cloud-check": CloudCheck,
  "cloud-off": CloudOff,
  "cloud-rain": CloudRain,
  copy: Copy,
  download: Download,
  ellipsis: Ellipsis,
  "external-link": ExternalLink,
  file: File,
  "file-plus": FilePlus,
  "file-stack": FileStack,
  "file-text": FileText,
  "file-type": FileType,
  "file-x": FileX,
  filter: Filter,
  folder: Folder,
  "folder-input": FolderInput,
  "folder-minus": FolderMinus,
  "folder-open": FolderOpen,
  "folder-plus": FolderPlus,
  gem: Gem,
  "git-compare-arrows": GitCompareArrows,
  globe: Globe,
  "grip-vertical": GripVertical,
  hash: Hash,
  history: History,
  home: Home,
  image: Image,
  info: Info,
  italic: Italic,
  "key-round": KeyRound,
  "layout-grid": LayoutGrid,
  library: Library,
  lightbulb: Lightbulb,
  list: List,
  "list-filter": ListFilter,
  "list-indent-decrease": ListIndentDecrease,
  "list-indent-increase": ListIndentIncrease,
  "list-ordered": ListOrdered,
  "list-plus": ListPlus,
  "loader-circle": LoaderCircle,
  lock: Lock,
  "lock-open": LockOpen,
  "log-out": LogOut,
  mail: Mail,
  map: Map,
  "map-pin": MapPin,
  maximize: Maximize,
  "message-square": MessageSquare,
  "message-square-plus": MessageSquarePlus,
  minus: Minus,
  monitor: Monitor,
  moon: Moon,
  "move-horizontal": MoveHorizontal,
  "move-vertical": MoveVertical,
  "notebook-pen": NotebookPen,
  "notebook-tabs": NotebookTabs,
  orbit: Orbit,
  package: Package,
  "panel-bottom": PanelBottom,
  "panel-bottom-close": PanelBottomClose,
  "panel-left": PanelLeft,
  "panel-right": PanelRight,
  "panel-right-close": PanelRightClose,
  "panels-top-left": PanelsTopLeft,
  "pen-line": PenLine,
  pencil: Pencil,
  plus: Plus,
  printer: Printer,
  "redo-2": Redo2,
  "refresh-cw": RefreshCw,
  rocket: Rocket,
  "rotate-ccw": RotateCcw,
  "rotate-cw": RotateCw,
  save: Save,
  scan: Scan,
  scroll: Scroll,
  search: Search,
  "search-x": SearchX,
  send: Send,
  settings: Settings,
  sparkles: Sparkles,
  square: Square,
  star: Star,
  "sticky-note": StickyNote,
  strikethrough: Strikethrough,
  sun: Sun,
  "sun-moon": SunMoon,
  tag: Tag,
  "trash-2": Trash2,
  "triangle-alert": TriangleAlert,
  type: Type,
  underline: Underline,
  "undo-2": Undo2,
  upload: Upload,
  "user-cog": UserCog,
  "user-round": UserRound,
  "user-x": UserX,
  "users-round": UsersRound,
  waypoints: Waypoints,
  x: X,
  zap: Zap,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;
